name: Benchmark
on:
  push: {}
  workflow_dispatch: {}

jobs:
  monkci-remote-cache:
    name: Monk CI with Remote Cache
    runs-on: monkci-ubuntu-24.04-4
    defaults:
      run:
        working-directory: upstream
    env:
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7
      - run: ./script/linux # Install Dependencies
      - run: cargo build --release

  monkci-cacheless:
    name: Monk CI Cacheless
    runs-on: monkci-ubuntu-24.04-4
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7
      - run: ./script/linux # Install Dependencies
      - run: cargo build --release

  github-local-cache:
    name: GitHub with Local Cache
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: upstream
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7

      - name: Check sccache version
        run: sccache --version

      - name: Install Dependencies
        run: ./script/linux

      - name: Build with Cargo
        run: cargo build --release --verbose

  github-cacheless:
    name: Github Cacheless
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: upstream
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7
      - run: ./script/linux # Install Dependencies
      - run: cargo build --release